name: Deploy SafetyManager for EcoOnline


on: [workflow_dispatch]

concurrency: production_environment

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: SetUp PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: gd --with-freetype=/usr/include/ --with-png=/usr/include/ --with-jpeg=/usr/include/, zip, exif
          tools: deployer
          
      - name: install composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi --ignore-platform-reqs

      - name: Deploy
        uses: deployphp/action@v1
        with:
          deployer-version: "6.3.0"
          deployer-binary: "/vendor/bin/dep"
          dep: test
          verbosity: -vvv
          private-key: ${{ secrets.PRIVATE_KEY }}