name: Deploy SafetyManager for EcoOnline


on: [workflow_dispatch]

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: SetUp PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: freetype, libjpeg-turbo, libpng, freetype-dev, libjpeg-turbo-dev, libpng-dev, gd --with-freetype=/usr/include/ --with-png=/usr/include/ --with-jpeg=/usr/include/ \
          tools: deployer
          
      - name: Install composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Deploy
        uses: deployphp/action@v1
        with:
          dep: deploy
          private-key: ${{ secrets.PRIVATE_KEY }}